import BookCarousel from "../components/BookCarousel"

import { summaryData } from "../data/data"
import { carouselContainer, headingStyle, mainStyle } from "../styles";

export default async function Page() {
    const data = await summaryData();

    return (
    <>
    <main className={mainStyle}>
      <div className="container mx-auto px-4 py-12">
        {/* Hero Section */}
        <div className="grid md:grid-cols-2 gap-8 mb-16">
          <div className="space-y-6">
            <h1 className="text-3xl md:text-4xl font-bold text-gray-900">
              About this project
            </h1>
            <div className="prose prose-lg text-gray-600">
              <p>
                This carousel displays some basic information about my book collection. It may not be very exciting in itself, but it is based on SQL queries against a PostgreSQL database, so it updates automatically when new books are added. Schema validation is done with <a className="text-blue-600 underline" href="https://zod.dev/">zod</a>. The carousel was built using <a className="text-blue-600 underline" href="https://www.npmjs.com/package/react-multi-carousel">react-multi-carousel 2.8.5</a>, which I heartily recommend.
              </p>
            </div>
          </div>
          <div className="relative h-64 md:h-auto rounded-xl overflow-hidden bg-blue-100">
            <img
              src="/bookshelf.jpg"
              alt="Library collection"
              className="w-full h-full object-cover"
            />
          </div>
        </div>

        {/* Stats Section */}
        <div className="bg-white shadow-lg rounded-xl p-6 mb-16">
          <h2 className="text-2xl md:text-3xl font-semibold text-gray-800 mb-6">
            Collection Overview
          </h2>
          <BookCarousel data={data} />
        </div>

        {/* Additional Information Section */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div className="bg-blue-50 rounded-xl p-8 shadow-sm">
            <h3 className="text-xl font-semibold text-blue-900 mb-4">
              The Collection
            </h3>
            <p className="text-blue-800">
              I'm not wealthy enough to be a very serious book collector, but my research on the early modern period has given me an interest in early printed books. Some of the books here were rescued from a skip (!!), some were picked up in second-hand shops, and some are from online auctions. Any new books I pick up are added via the frontend (see the add book link above). I intend to look into storing my image files more efficiently in Vercel Blob (at the moment images are linked from a dropbox account, which means they may load slowly).
            </p>
          </div>
          
          <div className="bg-emerald-50 rounded-xl p-8 shadow-sm">
            <h3 className="text-xl font-semibold text-emerald-900 mb-4">
              Security
            </h3>
            <p className="text-emerald-800">
              I have implemented authentication and authorisation using <a className="text-blue-600 underline" href="https://jose.readthedocs.io/en/latest/">jose</a>. If you'd like to create an account, all that is needed is an email and password. (The email needs to be in a valid format but will not be used for any purpose; it doesn't have to be your actual email address.) Passwords are hashed using <a className="text-blue-600 underline" href="https://www.npmjs.com/package/bcrypt">bcrypt</a> before being saved to the database; sessions currently expire after 7 days. I am looking into adding oauth login via GitHub and Google as well.
            </p>
          </div>

          <div className="bg-purple-50 rounded-xl p-8 shadow-sm">
            <h3 className="text-xl font-semibold text-purple-900 mb-4">
              Layout & Design
            </h3>
            <p className="text-purple-800">
              I'm capable of implementing other people's designs, but I would never pretend to be a designer myself. Most of the general look for this site (but none of the functionality) was AI-generated, although I have picked up ideas from elsewhere too. I am in the process of refactoring the HTML/CSS code generated by Claude.AI to turn it into more readable and reusable React components.
            </p>
          </div>
        </div>
      </div>
    </main>
  </>)
}
